Img:
  ImageFolder: "app-data/images"
  DownloadTimeout: 5000
Cache:
  CacheSize: 524288000 #500
  CachePath: "app-data/cache/data.json"
Logging:
  ErrorLog:
    FileName: "app-data/log/error.log"
    MaxBackups: 3
    MaxAge: 28 #days
  AccessLog:
    FileName: "app-data/log/access.log"
    MaxBackups: 3
    MaxAge: 28 #days